[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[features]
debug = ["essentials/dotenv"]
default = ["cors"]
cors = []

[workspace]
members = ["helper", "helper-macros"]
resolver = "2"

[workspace.dependencies]
essentials = { tag = "v0.3.1", git = "https://github.com/majksa-dev/rust-essentials", default-features = false, features = ["log"] }

[dependencies]
essentials.workspace = true
serde = "1.0.203"
serde_json = "1.0.114"
pingora = { version = "0.2.0", features = ["proxy"] }
regex = "1.10.3"
async-trait = "0.1.77"
structopt = "0.3.26"
redis = "0.25.0"
tokio = { version = "1", features = ["full"] }
snedfile = { version = "0.1", features = ["large-files"]}
http = "1.1.0"

[dev-dependencies]
helper = { path = "helper" }
wiremock = "0.6.0"
tokio = { version = "1", features = ["full"] }
assert_fs = { version = "1.1.1", features = ["color"] }
surf = "2.3.2"
