[package]
name = "gateway"
version = "0.2.0"
edition = "2021"

[features]
debug = ["essentials/dotenv"]
default = ["cors"]
cors = []

[dependencies]
essentials = { tag = "v0.3.1", git = "https://github.com/majksa-dev/rust-essentials", default-features = false, features = ["log"] }
async-trait = "0.1.77"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }
http = "1.1.0"

[dev-dependencies]
testing-utils = { tag = "v0.1.2", git = "https://github.com/majksa-dev/rust-testing-utils" }
pretty_assertions = "1.4.0"
wiremock = "0.6.0"
