name: Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  rust:
    uses: majksa-actions/workflows/.github/workflows/rust-test.yml@v1
    with:
      features: '["","auth","cors","rate-limit","cache","middlewares"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
